Importar as bibliotecas

In [2]:
# Importa a biblioteca Pandas para manipulação e análise dos dados.
import pandas as pd

# Importa a biblioteca NumPy para operações numéricas.
import numpy as np

# Importa a função train_test_split para dividir os dados em treinamento e teste.
from sklearn.model_selection import train_test_split

Carregamento do dataset

In [3]:
# Define o caminho relativo para o arquivo CSV que está dentro da pasta data/raw.
caminho_dataset = "../data/raw/DATASET - Dataset_limpo_V1.csv"

# Lê o arquivo CSV e armazena os dados em um DataFrame chamado df.
df = pd.read_csv(caminho_dataset)

# Exibe as cinco primeiras linhas do dataset para verificar se o carregamento ocorreu corretamente.
df.head()

,Mensagem,solicita_senha,solicita_codigo_autenticacao,solicita_dados_bancarios,solicita_dados_pessoais,solicita_dados_cartao,solicita_atualizacao_cadastro,solicita_pagamento,solicita_clique,solicita_ligacao,...,possui_reembolso,possui_vantagem_inesperada,possui_oferta_financeira,possui_url,possui_url_encurtada,possui_telefone,possui_pix,possui_erros_ortografia_gramatica,possui_chamada_acao,possivel_golpe
0,Sabia que da pra curtir tudo da Claro? 350 MEG...,0,0,0,0,0,0,0,1,1,...,0,0,1,1,1,1,0,1,1,0
1,Seu dia a dia pede MUITA INTERNET! Entao vem p...,0,0,0,0,0,0,0,1,0,...,0,0,1,1,1,0,0,1,1,0
2,"Cliente Claro,nao identificamos pgt fat do ser...",0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,1,1,0
3,Claro Multi ta na sua com oferta especial: 600...,0,0,0,0,0,0,0,1,1,...,0,0,1,1,1,1,0,1,1,0
4,Claro Multi ta na sua com oferta especial: 600...,0,0,0,0,0,0,0,1,1,...,0,0,1,1,1,1,0,1,1,0

Verificar informações gerais do dataset

In [4]:
# Exibe informações gerais sobre o DataFrame, incluindo quantidade de valores,
# valores ausentes e tipos de dados de cada coluna.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1347 entries, 0 to 1346
Data columns (total 26 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Mensagem                           1347 non-null   str
 1   solicita_senha                     1347 non-null   int64
 2   solicita_codigo_autenticacao       1347 non-null   int64
 3   solicita_dados_bancarios           1347 non-null   int64
 4   solicita_dados_pessoais            1347 non-null   int64
 5   solicita_dados_cartao              1347 non-null   int64
 6   solicita_atualizacao_cadastro      1347 non-null   int64
 7   solicita_pagamento                 1347 non-null   int64
 8   solicita_clique                    1347 non-null   int64
 9   solicita_ligacao                   1347 non-null   int64
 10  menciona_bloqueio_conta            1347 non-null   int64
 11  carga_emocional                    1347 non-null   str
 12  possui_urgencia                    1347 non-null   int64
 13  possui_ameaca                      1347 non-null   int64
 14  possui_linguagem_alarmista         1347 non-null   int64
 15  possui_recompensa                  1347 non-null   int64
 16  possui_reembolso                   1347 non-null   int64
 17  possui_vantagem_inesperada         1347 non-null   int64
 18  possui_oferta_financeira           1347 non-null   int64
 19  possui_url                         1347 non-null   int64
 20  possui_url_encurtada               1347 non-null   int64
 21  possui_telefone                    1347 non-null   int64
 22  possui_pix                         1347 non-null   int64
 23  possui_erros_ortografia_gramatica  1347 non-null   int64
 24  possui_chamada_acao                1347 non-null   int64
 25  possivel_golpe                     1347 non-null   int64
dtypes: int64(24), str(2)
memory usage: 423.7 KB

Vamos verificar quais valores existem nela (POSSIVEL GOLPE):

In [7]:
# Conta quantas ocorrências existem de cada classe na coluna "Possivel golpe".
df["possivel_golpe"].value_counts()

possivel_golpe
0    833
1    514
Name: count, dtype: int64

Separar features e variável-alvo

nossa variável-alvo:

In [8]:
# Define o nome da coluna que representa a variável que queremos prever.
coluna_alvo = "possivel_golpe"

classes existentes:

In [9]:
# Exibe as classes existentes na variável-alvo.
df[coluna_alvo].unique()

array([0, 1])

Separar X e y

In [10]:
# Cria o DataFrame X contendo todas as colunas utilizadas como características.
X_atributos = df.drop(columns=[coluna_alvo])

# Cria a variável y contendo somente a coluna que queremos prever.
y_target = df[coluna_alvo]

Vamos conferir:

In [15]:
# Exibe as dimensões das características utilizadas pelo modelo.
X_atributos.shape
# Exibe as primeiras linhas das características utilizadas pelo modelo.
X_atributos.head()

,Mensagem,solicita_senha,solicita_codigo_autenticacao,solicita_dados_bancarios,solicita_dados_pessoais,solicita_dados_cartao,solicita_atualizacao_cadastro,solicita_pagamento,solicita_clique,solicita_ligacao,...,possui_recompensa,possui_reembolso,possui_vantagem_inesperada,possui_oferta_financeira,possui_url,possui_url_encurtada,possui_telefone,possui_pix,possui_erros_ortografia_gramatica,possui_chamada_acao
0,Sabia que da pra curtir tudo da Claro? 350 MEG...,0,0,0,0,0,0,0,1,1,...,0,0,0,1,1,1,1,0,1,1
1,Seu dia a dia pede MUITA INTERNET! Entao vem p...,0,0,0,0,0,0,0,1,0,...,0,0,0,1,1,1,0,0,1,1
2,"Cliente Claro,nao identificamos pgt fat do ser...",0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,1,1
3,Claro Multi ta na sua com oferta especial: 600...,0,0,0,0,0,0,0,1,1,...,0,0,0,1,1,1,1,0,1,1
4,Claro Multi ta na sua com oferta especial: 600...,0,0,0,0,0,0,0,1,1,...,0,0,0,1,1,1,1,0,1,1

In [16]:
# Exibe a quantidade de registros existentes na variável-alvo.
y_target.shape
# Exibe as primeiras linhas da variável-alvo.
y_target.head()

0    0
1    0
2    0
3    0
4    0
Name: possivel_golpe, dtype: int64

Separação

df
 ├── dataset completo

X
 └── características que serão utilizadas pelo modelo

mensagens
 └── texto original dos SMS

y
 └── "Possivel golpe" → Sim / Não

Separando mensagens

In [17]:
# Cria uma variável contendo somente o texto original das mensagens SMS.
mensagens = X_atributos["Mensagem"]

Remove temporariamente a coluna de texto dos atributos estruturados.

In [18]:
# Remove temporariamente a coluna de texto dos atributos estruturados.
X_atributos = X_atributos.drop(columns=["Mensagem"])

Conferir novamente as colunas

In [22]:
# Exibe os nomes das colunas que atualmente fazem parte dos atributos estruturados.
y_target.tolist()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 ...]

Transformar carga_emocional em números
Baixo → 0
Médio → 1
Alto → 2

In [24]:
# Cria um dicionário que associa cada nível de carga emocional a um valor numérico.
mapa_carga_emocional = {
    "Baixo": 0,
    "Médio": 1,
    "Alto": 2
}

Agora aplicamos a transformação:

In [25]:
# Substitui os níveis de carga emocional pelos respectivos valores numéricos.
X_atributos["carga_emocional"] = X_atributos["carga_emocional"].map(mapa_carga_emocional)

Confira o resultado:

In [26]:
# Exibe os primeiros valores da coluna após a transformação para números.
X_atributos["carga_emocional"].head()

0    0
1    0
2    1
3    0
4    0
Name: carga_emocional, dtype: int64

In [31]:
# Exibe os valores únicos existentes após a transformação.
X_atributos["carga_emocional"].unique()

array([0, 1, 2])

Conferir os tipos das features

In [32]:
# Exibe os tipos de dados de todas as características estruturadas.
X_atributos.dtypes

solicita_senha                       int64
solicita_codigo_autenticacao         int64
solicita_dados_bancarios             int64
solicita_dados_pessoais              int64
solicita_dados_cartao                int64
solicita_atualizacao_cadastro        int64
solicita_pagamento                   int64
solicita_clique                      int64
solicita_ligacao                     int64
menciona_bloqueio_conta              int64
carga_emocional                      int64
possui_urgencia                      int64
possui_ameaca                        int64
possui_linguagem_alarmista           int64
possui_recompensa                    int64
possui_reembolso                     int64
possui_vantagem_inesperada           int64
possui_oferta_financeira             int64
possui_url                           int64
possui_url_encurtada                 int64
possui_telefone                      int64
possui_pix                           int64
possui_erros_ortografia_gramatica    int64
possui_chamada_acao                  int64
dtype: object

In [33]:
# Exibe os valores únicos encontrados em cada característica.
for coluna in X_atributos.columns:
    # Exibe o nome da característica e seus valores únicos.
    print(coluna, X_atributos[coluna].unique())

solicita_senha [0 1]
solicita_codigo_autenticacao [0 1]
solicita_dados_bancarios [0 1]
solicita_dados_pessoais [0 1]
solicita_dados_cartao [0 1]
solicita_atualizacao_cadastro [0 1]
solicita_pagamento [0 1]
solicita_clique [1 0]
solicita_ligacao [1 0]
menciona_bloqueio_conta [0 1]
carga_emocional [0 1 2]
possui_urgencia [0 1]
possui_ameaca [0 1]
possui_linguagem_alarmista [0 1]
possui_recompensa [0 1]
possui_reembolso [0 1]
possui_vantagem_inesperada [0 1]
possui_oferta_financeira [1 0]
possui_url [1 0]
possui_url_encurtada [1 0]
possui_telefone [1 0]
possui_pix [0 1]
possui_erros_ortografia_gramatica [1 0]
possui_chamada_acao [1 0]

Verificar a relação entre as features e o target

In [34]:
# Cria uma cópia dos atributos estruturados para realizar análises sem modificar o DataFrame original.
dados_analise = X_atributos.copy()

# Adiciona a variável-alvo ao DataFrame temporário para permitir a análise conjunta das variáveis.
dados_analise["y_target"] = y_target

In [35]:
# Calcula a correlação entre todas as variáveis numéricas do DataFrame.
matriz_correlacao = dados_analise.corr(numeric_only=True)

# Exibe a correlação de cada atributo com a variável-alvo.
matriz_correlacao["y_target"].sort_values(ascending=False)

y_target                             1.000000
carga_emocional                      0.741389
possui_linguagem_alarmista           0.696318
possui_urgencia                      0.670424
possui_chamada_acao                  0.565576
menciona_bloqueio_conta              0.499939
possui_ameaca                        0.491720
solicita_clique                      0.410928
possui_url                           0.401502
possui_vantagem_inesperada           0.357623
possui_pix                           0.297067
solicita_dados_pessoais              0.264230
solicita_atualizacao_cadastro        0.261753
possui_recompensa                    0.236674
solicita_dados_cartao                0.207926
possui_oferta_financeira             0.206723
solicita_senha                       0.198319
solicita_pagamento                   0.167420
possui_reembolso                     0.134845
solicita_dados_bancarios             0.111364
solicita_ligacao                    -0.002751
possui_telefone                     -0.006265
solicita_codigo_autenticacao        -0.177010
possui_erros_ortografia_gramatica   -0.192981
possui_url_encurtada                -0.197993
Name: y_target, dtype: float64

Analisar cada feature contra o target

In [36]:
# Percorre todas as colunas existentes nos atributos estruturados.
for coluna in X_atributos.columns:
    
    # Exibe o nome da característica que está sendo analisada.
    print(f"\nCaracterística: {coluna}")
    
    # Calcula a proporção de mensagens classificadas como golpe para cada valor da característica.
    proporcao_golpe = dados_analise.groupby(coluna)["y_target"].mean()
    
    # Exibe a proporção calculada para cada valor da característica.
    print(proporcao_golpe)

Característica: solicita_senha
solicita_senha
0    0.365854
1    0.971429
Name: y_target, dtype: float64

Característica: solicita_codigo_autenticacao
solicita_codigo_autenticacao
0    0.410405
1    0.125000
Name: y_target, dtype: float64

Característica: solicita_dados_bancarios
solicita_dados_bancarios
0    0.375657
1    0.875000
Name: y_target, dtype: float64

Característica: solicita_dados_pessoais
solicita_dados_pessoais
0    0.350863
1    0.917808
Name: y_target, dtype: float64

Característica: solicita_dados_cartao
solicita_dados_cartao
0    0.365091
1    1.000000
Name: y_target, dtype: float64

Característica: solicita_atualizacao_cadastro
solicita_atualizacao_cadastro
0    0.351373
1    0.916667
Name: y_target, dtype: float64

Característica: solicita_pagamento
solicita_pagamento
0    0.341057
1    0.544776
Name: y_target, dtype: float64

Característica: solicita_clique
solicita_clique
0    0.209573
1    0.613240
Name: y_target, dtype: float64

Característica: solicita_ligacao
solicita_ligacao
0    0.381995
1    0.377193
Name: y_target, dtype: float64

Característica: menciona_bloqueio_conta
menciona_bloqueio_conta
0    0.282872
1    0.979058
Name: y_target, dtype: float64

Característica: carga_emocional
carga_emocional
0    0.031977
1    0.599174
2    0.832134
Name: y_target, dtype: float64

Característica: possui_urgencia
possui_urgencia
0    0.128571
1    0.800789
Name: y_target, dtype: float64

Característica: possui_ameaca
possui_ameaca
0    0.283608
1    0.963918
Name: y_target, dtype: float64

Característica: possui_linguagem_alarmista
possui_linguagem_alarmista
0    0.159405
1    0.896552
Name: y_target, dtype: float64

Característica: possui_recompensa
possui_recompensa
0    0.345306
1    0.745902
Name: y_target, dtype: float64

Característica: possui_reembolso
possui_reembolso
0    0.373965
1    0.944444
Name: y_target, dtype: float64

Característica: possui_vantagem_inesperada
possui_vantagem_inesperada
0    0.318487
1    0.859873
Name: y_target, dtype: float64

Característica: possui_oferta_financeira
possui_oferta_financeira
0    0.329567
1    0.575439
Name: y_target, dtype: float64

Característica: possui_url
possui_url
0    0.212240
1    0.606218
Name: y_target, dtype: float64

Característica: possui_url_encurtada
possui_url_encurtada
0    0.419966
1    0.140541
Name: y_target, dtype: float64

Característica: possui_telefone
possui_telefone
0    0.382545
1    0.371901
Name: y_target, dtype: float64

Característica: possui_pix
possui_pix
0    0.338983
1    0.870370
Name: y_target, dtype: float64

Característica: possui_erros_ortografia_gramatica
possui_erros_ortografia_gramatica
0    0.457565
1    0.265918
Name: y_target, dtype: float64

Característica: possui_chamada_acao
possui_chamada_acao
0    0.02400
1    0.59268
Name: y_target, dtype: float64

Verificar se alguma feature é igual ao target

In [37]:
# Percorre todas as características existentes no conjunto de atributos.
for coluna in X_atributos.columns:
    
    # Verifica se os valores da característica são exatamente iguais aos valores da variável-alvo.
    possui_mesmos_valores = X_atributos[coluna].equals(y_target)
    
    # Exibe o resultado da comparação para a característica analisada.
    print(f"{coluna}: {possui_mesmos_valores}")

solicita_senha: False
solicita_codigo_autenticacao: False
solicita_dados_bancarios: False
solicita_dados_pessoais: False
solicita_dados_cartao: False
solicita_atualizacao_cadastro: False
solicita_pagamento: False
solicita_clique: False
solicita_ligacao: False
menciona_bloqueio_conta: False
carga_emocional: False
possui_urgencia: False
possui_ameaca: False
possui_linguagem_alarmista: False
possui_recompensa: False
possui_reembolso: False
possui_vantagem_inesperada: False
possui_oferta_financeira: False
possui_url: False
possui_url_encurtada: False
possui_telefone: False
possui_pix: False
possui_erros_ortografia_gramatica: False
possui_chamada_acao: False

Se o target estiver como 0 e 1
0 → Não golpe
1 → Possível golpe

In [42]:
# Define o valor 0 como a classe correspondente a uma mensagem que não é considerada possível golpe.
classe_nao_golpe = 0

# Define o valor 1 como a classe correspondente a uma mensagem considerada possível golpe.
classe_possivel_golpe = 1

Divisão entre treino e teste

O modelo deve aprender usando uma parte dos dados e ser avaliado em dados que ele nunca viu durante o treinamento.

Vamos utilizar inicialmente:

80% → treinamento
20% → teste

Dividir as mensagens

In [ ]:
# Divide as mensagens em dois conjuntos: mensagens para treinamento e mensagens para teste.
mensagens_treino, mensagens_teste, y_target_treino, y_target_teste = train_test_split(
    mensagens,
    y_target,
    test_size=0.20,
    random_state=42,
    stratify=y_target
)

Dividir também os atributos estruturados

In [44]:
# Divide os atributos estruturados em conjuntos de treinamento e teste.
X_atributos_treino, X_atributos_teste, _, _ = train_test_split(
    X_atributos,
    y_target,
    test_size=0.20,
    random_state=42,
    stratify=y_target
)

                    DATASET
                       │
             ┌─────────┴─────────┐
             │                   │
          80% treino          20% teste
             │                   │
      ┌──────┴──────┐      ┌─────┴─────┐
      │             │      │           │
   Mensagem     Atributos Mensagem  Atributos
      │             │      │           │
      └──────┬──────┘      └─────┬─────┘
             │                   │
             ▼                   ▼
        Treinamento            Avaliação

Pré-processamento do texto

converter para letras minúsculas;
remover espaços extras;
tratar valores ausentes.

In [46]:
# Importa a biblioteca re para trabalhar com expressões regulares.
import re

In [47]:
# Define uma função responsável pela normalização básica de uma mensagem.
def normalizar_mensagem(mensagem):
    
    # Verifica se o conteúdo recebido é nulo.
    if pd.isna(mensagem):
        
        # Retorna uma string vazia caso a mensagem esteja ausente.
        return ""
    
    # Converte o conteúdo da mensagem para texto.
    mensagem = str(mensagem)
    
    # Converte todas as letras da mensagem para minúsculas.
    mensagem = mensagem.lower()
    
    # Substitui sequências de espaços, quebras de linha e tabulações por um único espaço.
    mensagem = re.sub(r"\s+", " ", mensagem)
    
    # Remove espaços desnecessários existentes no início e no final da mensagem.
    mensagem = mensagem.strip()
    
    # Retorna a mensagem normalizada.
    return mensagem

Exemplo:

In [49]:
# Seleciona a primeira mensagem do conjunto de treinamento.
mensagem_exemplo = mensagens_treino.iloc[0]

# Exibe a mensagem original para comparação.
print("Mensagem original:")
print(mensagem_exemplo)

# Aplica a função de normalização à mensagem selecionada.
mensagem_normalizada = normalizar_mensagem(mensagem_exemplo)

# Exibe a mensagem depois da normalização.
print("\nMensagem normalizada:")
print(mensagem_normalizada)

Mensagem original:
ALERTA BANCO INTER: Tentativa de login efetuada a partir de um dispositivo não reconhecido. Bloqueie em: https://bancointer-bloqueio-acesso.site

Mensagem normalizada:
alerta banco inter: tentativa de login efetuada a partir de um dispositivo não reconhecido. bloqueie em: https://bancointer-bloqueio-acesso.site

Aplicando:

In [50]:
# Cria uma versão normalizada das mensagens utilizadas no treinamento.
mensagens_treino_normalizadas = mensagens_treino.apply(normalizar_mensagem)

# Cria uma versão normalizada das mensagens utilizadas no teste.
mensagens_teste_normalizadas = mensagens_teste.apply(normalizar_mensagem)

Conferir o resultado

In [52]:
# Exibe algumas mensagens depois da normalização.
print("Mensagens normalizadas:")

# Exibe as cinco primeiras mensagens após a normalização.
print(mensagens_treino_normalizadas.head())

Mensagens normalizadas:
1310    alerta banco inter: tentativa de login efetuad...
637     boa tarde. me manda sua senha. confirma aqui h...
875     detran-sp: sua cnh sera suspensa por atingir o...
236     santander: <nome>, seu cartao ja esta nos corr...
794     oi <nome>, o comprovante do pix da sua parte d...
Name: Mensagem, dtype: str

                 MENSAGEM SMS
                      │
             ┌────────┴────────┐
             │                 │
             ▼                 ▼
       Texto original     Features
             │             estruturadas
             │                 │
             ▼                 │
           TF-IDF              │
             │                 │
             └────────┬────────┘
                      ▼
                 MODELO ML
                      │
                      ▼
                y_target
              0 = Não golpe
              1 = Possível golpe

Próximo passo

Agora que o texto está normalizado, o próximo passo será transformar as mensagens em números utilizando TF-IDF.

Mas existe um ponto crucial que quero que você entenda antes de fazermos isso:

O TF-IDF será ajustado (fit) somente nas mensagens de treinamento.

Depois faremos apenas transform nas mensagens de teste.

Isso é exatamente para evitar data leakage.

Transformação do texto com TF-IDF

In [53]:
# Importa o transformador TF-IDF da biblioteca Scikit-learn.
from sklearn.feature_extraction.text import TfidfVectorizer

Criar o vetor TF-IDF

In [54]:
# Cria o vetor TF-IDF que será utilizado para transformar as mensagens em valores numéricos.
vetorizador_tfidf = TfidfVectorizer()

Fazer o fit_transform somente no treinamento

fit
 ↓
aprende o vocabulário do treinamento

transform
 ↓
converte as mensagens em números

In [55]:
# Aprende o vocabulário e os pesos TF-IDF utilizando somente as mensagens de treinamento.
mensagens_treino_tfidf = vetorizador_tfidf.fit_transform(mensagens_treino_normalizadas)

Transformar o conjunto de teste

In [56]:
# Utiliza o vocabulário aprendido no treinamento para transformar as mensagens de teste.
mensagens_teste_tfidf = vetorizador_tfidf.transform(mensagens_teste_normalizadas)

Verificar o tamanho das matrizes

In [57]:
# Exibe a quantidade de mensagens e características TF-IDF existentes no conjunto de treinamento.
print("Formato TF-IDF treinamento:", mensagens_treino_tfidf.shape)

# Exibe a quantidade de mensagens e características TF-IDF existentes no conjunto de teste.
print("Formato TF-IDF teste:", mensagens_teste_tfidf.shape)

Formato TF-IDF treinamento: (1077, 2851)
Formato TF-IDF teste: (270, 2851)

Guardar o vetor para uso futuro

In [ ]:
# Importa o módulo joblib para salvar objetos Python no disco.
import joblib

Um detalhe importante do nosso projeto
X_atributos_treino
        +
mensagens_treino_tfidf
        │
        ▼
 informações para treinamento
 
 X_atributos_teste
        +
mensagens_teste_tfidf
        │
        ▼
 informações para avaliação

Agora precisamos juntar essas duas fontes de informação:

Texto do SMS + características estruturadas → entrada final do modelo

Combinar TF-IDF com os atributos estruturados

In [61]:
# Importa a função hstack para combinar matrizes horizontalmente.
from scipy.sparse import hstack

# Converte os atributos estruturados de treinamento para uma matriz NumPy.
atributos_treino_array = X_atributos_treino.to_numpy()

# Converte os atributos estruturados de teste para uma matriz NumPy.
atributos_teste_array = X_atributos_teste.to_numpy()

# Combina as características TF-IDF com os atributos estruturados do treinamento.
X_treino_final = hstack([mensagens_treino_tfidf, atributos_treino_array])

# Combina as características TF-IDF com os atributos estruturados do teste.
X_teste_final = hstack([mensagens_teste_tfidf, atributos_teste_array])

Guardar os nomes das características

In [64]:
# Obtém a lista com os nomes das características estruturadas.
nomes_atributos = X_atributos.columns.tolist()

# Obtém a lista com os termos que foram aprendidos pelo TF-IDF.
nomes_tfidf = vetorizador_tfidf.get_feature_names_out().tolist()

# Combina os nomes das características de texto com os nomes das características estruturadas.
nomes_features = nomes_tfidf + nomes_atributos

# Exibe a quantidade total de nomes de características.
print("Total de features:", len(nomes_features))

Total de features: 2875

Salvar tudo que foi preparado

In [66]:
# Importa a biblioteca joblib para salvar objetos Python em arquivos.
import joblib

In [67]:
# Cria um dicionário vazio para armazenar os objetos preparados.
dados_preparados = {}

# Armazena as características finais utilizadas no treinamento.
dados_preparados["X_treino_final"] = X_treino_final

# Armazena as características finais utilizadas no teste.
dados_preparados["X_teste_final"] = X_teste_final

# Armazena os valores alvo utilizados no treinamento.
dados_preparados["y_treino"] = y_treino

# Armazena os valores alvo utilizados no teste.
dados_preparados["y_teste"] = y_teste

# Armazena o vetorizador TF-IDF treinado.
dados_preparados["vetorizador_tfidf"] = vetorizador_tfidf

# Armazena os nomes de todas as características utilizadas pelo modelo.
dados_preparados["nomes_features"] = nomes_features

# Salva todos os dados preparados dentro da pasta de dados processados.
joblib.dump(dados_preparados, "../data/processed/dados_preparados.joblib")

['../data/processed/dados_preparados.joblib']